// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using books.Data;

#nullable disable

namespace books.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20260225125344_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("books.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Толстой",
                            Count = 5,
                            Genre = "Роман",
                            Title = "Война и Мир",
                            Year = 1867
                        },
                        new
                        {
                            Id = 2,
                            Author = "Оруэлл",
                            Count = 3,
                            Genre = "Антиутопия",
                            Title = "1984",
                            Year = 1949
                        },
                        new
                        {
                            Id = 3,
                            Author = "Достоевский",
                            Count = 4,
                            Genre = "Роман",
                            Title = "Преступление и Наказание",
                            Year = 1866
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
